# recurring parameters for every run
[pytest]
minversion = 6.0
filterwarnings = ignore::DeprecationWarning
python_files = test_*.py
;python_classes = Check
python_functions = test_*

 addopts = --headed --browser chromium
; addopts =  -v -s --html=./out/test_report.html
; addopts = -s -vs -rf -rp --capture=no --junit-xml=./out/test_result.xml --html=./out/test_report.html --self-contained-html

markers =
    smoke
    regression
    functional
